#!/usr/bin/env bash

set -euo pipefail

usage="usage: $(basename "$0") [-h] [-t <target-host>]"

parsed=$(getopt -o ht: --l help,target-host: --name "$0" -- "$@")
eval set -- "$parsed"

target_host="${TARGET_HOST:-}"

while true; do
  case $1 in
    -h|--help)
      echo "$usage"
      exit 0
      ;;
    -t|--target_host)
      target_host="$2"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      fail "internal error"
      ;;
  esac
done

: "${target_host:?Missing -t}"

set -x

# Pre-installation tasks
sudo mkdir -p /mnt/persistent/etc
sudo cp -a /etc/machine-id /mnt/persistent/etc/
sudo mkdir -p /mnt/persistent/etc/ssh
sudo cp -a /tmp/pass-user-* /mnt/persistent/etc/

# Installation
sudo nixos-install --flake ".#$target_host" --no-root-passwd

# Post-installation tasks
sudo cp -ar /mnt/etc/ssh/authorized_keys.d /mnt/persistent/etc/ssh/
sudo umount /mnt/boot*
sudo zpool export -a
