#!/usr/bin/env bash

set -euo pipefail

usage="usage: $(basename "$0") [-h] [-t <target-host>] "
usage+='[-d <disks-list-nix-expr>] [-p <zpools-list-nix-expr>] -- '
usage+='[<extra-disko-args>...]'

parsed=$(getopt -o ht:d:p: -l help,target-host:,disks:,pools: -n "$0" -- "$@")
eval set -- "$parsed"

target_host="${TARGET_HOST:-}"
config_nix_args=()

while true; do
  case $1 in
    -h|--help)
      echo "$usage"
      exit 0
      ;;
    -t|--target-host)
      target_host="$2"
      shift 2
      ;;
    -d|--disks)
      config_nix_args+=("--arg disks $2")
      shift 2
      ;;
    -p|--pools)
      config_nix_args+=("--arg zpools $2")
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      fail "internal error"
      ;;
  esac
done

: "${target_host:?Missing -t}"

set -x

sudo nix run github:nix-community/disko \
  --extra-experimental-features 'nix-command flakes' \
  -- \
  --mode disko "./$target_host-disko.nix" \
  "${config_nix_args[@]}" \
  "$@"
