#!/usr/bin/env bash

password="${1:-password}"
my-mkpass -p "$password" /tmp/pass-zpool-rpool
my-mkpass -p "$password" -a sha-512 /tmp/pass-user-root
my-mkpass -p "$password" -a sha-512 /tmp/pass-user-nixos
