#!/usr/bin/env bash

set -euo pipefail

script_name=$(basename "$0")

usage() {
  local args='[-h] [-a <hash-algo>] [-p <explicit-password>] <output-file>'
  echo "usage: $script_name $args" >&2
  exit "${1:?}"
}

algo=''
password=''

while getopts ':ha:p:' opt; do
  case $opt in
    a) algo="$OPTARG";;
    p) password="$OPTARG";;
    h) usage 0;;
    *) usage 1;;
  esac
done
shift $((OPTIND-1))

output="${1:-}"
if [[ -z $output ]]; then
  echo -e "$script_name: missing output file\n"
  usage 1
fi

message="password ($output)"
verification="${password:-different}"

while [[ $password != "$verification" ]]; do
  echo >&2
  IFS= read -rsp "Enter $message: " password
  echo >&2
  IFS= read -rsp "Repeat $message: " verification
  echo >&2
done

if [[ -z $algo ]]; then
  hash_func='cat'
else
  hash_func="mkpasswd -m $algo -s"
fi

printf %s "$password" | $hash_func | sudo bash -c "umask 0377; cat > $output"
