#!/usr/bin/env bash

# Store plain-text or hashed & salted password in a file that is root-readable
# only. For non-plain-text storage, `mkpasswd` is used on the plain-text input.
#
# For linux login passwords, SHA-512 hashing algorithm must be used via the
# `-a sha-512` option.
# A plain-text password can be supplied via the `-p` option (e.g. for testing
# purposes), otherwise the password is read twice from stdin.

set -euo pipefail

script_name=$(basename "$0")

usage() {
  local args='[-h] [-a <hash-algo>] [-p <plain-text-password>] <output-file>'
  echo "usage: $script_name $args" >&2
  exit "${1:?}"
}

algo=''
password=''

while getopts ':ha:p:' opt; do
  case $opt in
    a) algo="$OPTARG";;
    p) password="$OPTARG";;
    h) usage 0;;
    *) usage 1;;
  esac
done
shift $((OPTIND-1))

output="${1:-}"
if [[ -z $output ]]; then
  echo -e "$script_name: missing output file\n"
  usage 1
fi

message="password ($output)"
verification="${password:-different}"

while [[ $password != "$verification" ]]; do
  echo >&2
  IFS= read -rsp "Enter $message: " password
  echo >&2
  IFS= read -rsp "Repeat $message: " verification
  echo >&2
done

if [[ -z $algo ]]; then
  # Transfer password untouched if `algo` is empty
  hash_func='cat'
else
  # Hash and salt password using algorith `algo`
  hash_func="mkpasswd -m $algo -s"
fi

printf %s "$password" | $hash_func | sudo bash -c "umask 0377; cat > $output"
