#!/usr/bin/env bash

set -euo pipefail

script_name=$(basename "$0")

_usage="
Usage: $script_name [-hn] [-d <disks-list-nix>] [-p <zpools-list-nix>]

Options:
  -d <disks-list-nix>     Nix expression of the list of disks IDs that should be
                          prepared.
  -h                      Display a help screen and quit.
  -n                      Perform a trial run only with no changes made.
  -p <zpools-list-nix>    Nix experssion of the list of ZFS pools that should be
                          prepared.
"

usage() { echo "$_usage" >&2; exit "${1:?}"; }

disko_args=()

while getopts ':hnd:p:' opt; do
  case $opt in
    d) disko_args+=("--arg disks $OPTARG");;
    p) disko_args+=("--arg zpools $OPTARG");;
    n) disko_args+=("--dry-run");;
    h) usage 0;;
    *) usage 1;;
  esac
done
shift $((OPTIND-1))

target_host="${TARGET_HOST:?}"
flake_dir="${FLAKE_DIR:?}"
disko_config="$flake_dir/hosts/$target_host-disko.nix"


set -x

sudo disko --mode disko "${disko_args[@]}" "$disko_config"
