#!/usr/bin/env bash

set -euo pipefail

script_name=$(basename "$0")

# Switch to script directory
cd "$(dirname -- "$0")"

usage() {
  local args='[-h] [-n] [-d <disks-list-nix-expr>] [-p <zpools-list-nix-expr>]'
  echo "usage: $script_name $args" >&2
  exit "${1:?}"
}

target_host_disko_config="${TARGET_HOST_DISKO_CONFIG:?}"
disko_args=()

while getopts ':hd:p:' opt; do
  case $opt in
    d) disko_args+=("--arg disks $OPTARG");;
    p) disko_args+=("--arg zpools $OPTARG");;
    n) disko_args+=("--dry-run");;
    h) usage 0;;
    *) usage 1;;
  esac
done
shift $((OPTIND-1))

set -x

sudo nix run github:nix-community/disko \
  --extra-experimental-features 'nix-command flakes' -- \
  --mode disko "${disko_args[@]}" "$target_host_disko_config"
